[package]
name = "fsrs"
version = "0.6.1"
authors = ["Open Spaced Repetition"]
categories = ["algorithms", "science"]
edition = "2021"
homepage = "https://github.com/open-spaced-repetition"
keywords = ["spaced-repetition", "algorithm", "fsrs", "machine-learning"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/open-spaced-repetition/fsrs-rs"
description = "FSRS for Rust, including Optimizer and Scheduler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies.burn]
# version = "0.11.1"
git = "https://github.com/open-spaced-repetition/burn.git"
rev = "404858e4db95c8f6ecd1d50d274aaf223c7bc1a7"
# path = "../burn/burn"
default-features = false
features = ["std", "train", "ndarray", "autodiff", "wasm-sync", "browser"]

[dependencies]
chrono = { version = "0.4.31", default-features = false, features = ["std", "clock"] }
chrono-tz = "0.8.4"
itertools = "0.12.0"
log = "0.4"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand = "0.8.5"
rayon = "1.8.0"
serde = "1.0.193"
snafu = "0.8.0"
strum = { version = "0.26.1", features = ["derive"] }
wasm-bindgen = "0.2.91"
