[package]
name = "fsrs-optimizer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { git = "https://github.com/burn-rs/burn.git", version = "0.9.0" }
burn-ndarray = { git = "https://github.com/burn-rs/burn.git", version = "0.9.0" }
burn-autodiff = { git = "https://github.com/burn-rs/burn.git", version = "0.9.0" }
serde = "1.0.183"
log = "0.4"
rusqlite = { version = "0.29.0" }
chrono = "0.4.26"
chrono-tz = "0.8.3"
itertools = "0.11.0"