[package]
name = "fsrs"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies.burn]
# version = "0.10.0"
git = "https://github.com/burn-rs/burn.git"
rev = "aa90fe8efbbba8d9aad8d67b5e5ed8e503ad8d44"
# path = "../burn/burn"
default-features = false
features = ["std", "train-minimal", "autodiff", "dataset-minimal", "ndarray"]

[dev-dependencies.burn]
# version = "0.10.0"
git = "https://github.com/burn-rs/burn.git"
rev = "aa90fe8efbbba8d9aad8d67b5e5ed8e503ad8d44"
# path = "../burn/burn"
features = ["train", "dataset-sqlite-bundled"]

[dependencies]
itertools = "0.11.0"
log = "0.4"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand = "0.8.5"
serde = "1.0.188"
snafu = "0.7.5"
strum = { version = "0.25.0", features = ["derive"] }
wasm-bindgen = "0.2.87"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock"] }
chrono-tz = "0.8.3"
criterion = { version = "0.5.1" }
rusqlite = { version = "0.29.0" }

[[bench]]
name = "benchmark"
harness = false
