[package]
name = "fsrs-optimizer"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.burn]
git = "https://github.com/burn-rs/burn.git"
rev = "36446e8d35694a9158f97e85e44b84544b8c4afb"
default-features = false
features = ["std", "train", "ndarray", "autodiff"]

[dev-dependencies.burn]
git = "https://github.com/burn-rs/burn.git"
rev = "36446e8d35694a9158f97e85e44b84544b8c4afb"
features = ["dataset-sqlite-bundled"]

[dependencies]
itertools = "0.11.0"
log = "0.4"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand = "0.8.5"
serde = "1.0.188"
snafu = "0.7.5"
strum = { version = "0.25.0", features = ["derive"] }

[dev-dependencies]
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock"] }
chrono-tz = "0.8.3"
rusqlite = { version = "0.29.0" }
